name: dockerhub-deploy
on:
  release:
    types: [created]

jobs:
  path-context:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
## courtesy of https://github.com/crazy-max/docker-build-push-action/blob/dbdfd86c1d1e402adeb2c6f293275ae35d99e982/README.md#tags-and-labels-handling
      -
        name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE=owasp/cwe-tool
          VERSION=noop
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          elif [[ $GITHUB_REF == refs/heads/* ]]; then
            VERSION=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
            if [ "${{ github.event.repository.default_branch }}" = "$VERSION" ]; then
              VERSION=edge
            fi
          elif [[ $GITHUB_REF == refs/pull/* ]]; then
            VERSION=pr-${{ github.event.number }}
          fi
          if [ "${{ github.event_name }}" != "pull_request" ]; then
            TAGS="${DOCKER_IMAGE}:sha-${GITHUB_SHA::8}"
          fi
          TAGS="${DOCKER_IMAGE}:${VERSION}"
          if [[ $VERSION =~ ^v[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
            MINOR=${VERSION%.*}
            MAJOR=${MINOR%.*}
            TAGS="$TAGS,${DOCKER_IMAGE}:${MINOR},${DOCKER_IMAGE}:${MAJOR},${DOCKER_IMAGE}:latest"
          fi
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
      # - name: Set sha tag
      #   id: tag
      #   run: echo ::set-output name=sha::$(echo ${GITHUB_REF} | cut -d'/' -f3)-${GITHUB_SHA}
      # - name: set version tag
      #   id: version
      #   run: echo ## cat from package.json?
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
#        if: ${{ secrets.DOCKERHUB_USERNAME=="lirantal" }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
 #       if: ${{ secrets.DOCKERHUB_USERNAME=="lirantal" }}
        with:
          context: .
          file: ./Dockerfile
          cache-from: type=registry,ref=owasp/cwe-tool:latest
          cache-to: type=inline
## platforms breaking?
#          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: ${{ steps.prep.outputs.tags }}
          labels: |
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.version=${{ steps.prep.outputs.version }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=${{ github.event.repository.license.name }}
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
#        if: ${{  github.actor=="OWASP" }}
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          # repository: owasp/cwe-tool/cwe-tool
          ## container registry
          #registry: ghcr.io
          #repository: owasp/cwe-tool
          tag_with_ref: true
